### PR TITLE
Fix/master/issue 11 www authenticate response header

### PR DESCRIPTION
**Pull request by travisspencer**
This PR provides new functionality to set the `WWW-Authenticate` header when no token is given in the request. The response includes the configured realm and scopes (if any). These new configuration settings are added to the README and the sample configuration.

### CODE REVIEW

**Comment by anestos** [comment]
Should `WWW-Authenticate` header only be added when no `Authorization` header is provided? Or should we add it when `Authorization` header is there but not of `Bearer` type and/or when the introspection call in Curity is that of an inactive token?

**Comment by travisspencer** [comment]
Hum, yes. I'll fix that.

We need to get some integration tests in place to verify both cases. Were
you working in something there? Can I piggyback in that or should I set
something up?

**Comment by anestos** [comment]
You can base of https://github.com/curityio/nginx_introspect/tree/fix/master/add-tests

You ll have to install Test::Nginx and build the source with static module
`cpan Test::Nginx`

**Comment by travisspencer** [comment]
- [ ] As a part of this PR, the intro of the README should be updated to say the exact version of Curity that is required.

**Pull request merged**
